name: Deploy Notely to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: <YOUR_GCP_PROJECT_ID>
  REGION: us-central1
  REPO_NAME: notely-ar-repo
  IMAGE_NAME: notely
  TAG: latest
  SERVICE_NAME: notely

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --region=${{ env.REGION }} \
            --allow-unauthenticated \
            --project=${{ env.PROJECT_ID }} \
            --max-instances=4 \
            --port=80

